In [26]:
import numpy as np
import mygrad as mg

In [27]:
class sigmoid():
    @staticmethod
    def activation(x):
        y = 1 / (1 + np.exp(-x))
        return y
    @staticmethod
    def prime(y):
        f = sigmoid.activation(y)
        return (f * (1 - f))

In [28]:
class softmax:
    @staticmethod
    def activation(x):
        # e_x = np.exp(x).reshape(-1,1)
        e_x = np.exp(x - np.max(x,axis=-1).reshape(-1,1))
        return e_x / e_x.sum(axis=-1).reshape(-1,1)
    @staticmethod
    def primeP(y): #marche pas
        n = y.shape[1]
        print(n,y.shape)
        i = np.identity(n)
        un = np.ones((n,y.shape[1]))
        SM = y.reshape((-1,1))
        print(SM.shape)
        jac = np.diagflat(y) - np.dot(SM, SM.T)
        j = np.dot((i* jac),un)
        # x = np.dot(jac,y.T)
        return j.T
    @staticmethod
    def prime(y):
        return(y * (1-y))

In [35]:
class BinaryCrossEntropy:
    def __init__(self, p, y,_m):
        self.p = p
        self.y = y
        self.m = _m
    def metrics(self):
        m = self.p.shape[0]
        return (-1 / m) * (np.sum((self.y * np.log(self.p + 1e-8)) + ((1 - self.y) * (np.log(1 - self.p + 1e-8)))))

    def forward(self):
    # -(y.log(p) + (1-y).log(1-p))
        return (-self.y * np.log(self.p + 1e-8)) + ((1 - self.y) * (np.log(1 - self.p + 1e-8)))

    def backward(self):
    # -(y/p + (1-y)/(1-p))
        return (-self.y/(self.p+1e-8) + (1 - self.y)/(1 - self.p))


In [36]:
np.random.seed(128)
x = np.random.randn(2,2)
y = np.array([[1,0,0],[0,1,0]])
w = np.random.randn(2,3)
b = np.zeros((3))
z = np.dot(x,w) + b
a = softmax.activation(z)
# a = sigmoid.activation(z)
print(a)
dL = a - y
dL

[[0.30830853 0.17855733 0.51313414]
 [0.24060612 0.66078529 0.0986086 ]]


array([[-0.69169147,  0.17855733,  0.51313414],
       [ 0.24060612, -0.33921471,  0.0986086 ]])

In [37]:
LossFct = BinaryCrossEntropy(a,y,0)
L = LossFct.forward()
L

array([[ 1.17665425, -0.19669312, -0.71976661],
       [-0.27523467,  0.41432631, -0.10381569]])

In [38]:
dL = LossFct.backward()
dL

array([[-3.24350407,  1.21737042,  2.05395382],
       [ 1.31683969, -1.51335087,  1.10939598]])

In [39]:
# da_dz = sigmoid.prime(a)
# da_dz = softmax.prime(a)
da_dz = softmax.prime(a)

print(da_dz)

[[0.21325438 0.14667461 0.24982749]
 [0.18271481 0.22414809 0.08888494]]


In [40]:
print(a-y)
print(L)
print(dL)
print(da_dz)
print((dL*da_dz))

[[-0.69169147  0.17855733  0.51313414]
 [ 0.24060612 -0.33921471  0.0986086 ]]
[[ 1.17665425 -0.19669312 -0.71976661]
 [-0.27523467  0.41432631 -0.10381569]]
[[-3.24350407  1.21737042  2.05395382]
 [ 1.31683969 -1.51335087  1.10939598]]
[[0.21325438 0.14667461 0.24982749]
 [0.18271481 0.22414809 0.08888494]]
[[-0.69169145  0.17855733  0.51313414]
 [ 0.24060612 -0.33921471  0.0986086 ]]


In [24]:
dL = LossFct.backward()
print(softmax.prime(L))
dL_da = np.dot(dL,softmax.prime(L))
dL_da

[[-0.20786097 -0.23538131 -1.23783058]
 [-0.3509888   0.24266002 -0.11459339]]


ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [25]:
i = np.identity(3)
un = np.ones((3,1))
j = np.dot((i* da_dz),un)
j

ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 